# ci-install.yml
# This workflow is triggered on push or pull request events to the main branch.
# It runs a series of jobs to set up the environment, install dependencies, and run tests.

name: CI with pip and conda
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - main

jobs:
  pip-test:
    name: Test pip install
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.11','3.12']
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
            token: ${{ secrets.GH_PAT }}
    
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install .
            pip install pytest pytest-cov

      - name: Check help menu
        run: popopolus --help

      - name: Run tests
        run:  |
          pytest test/ --cov=popopolus --cov-report=xml
  
  conda-test:
    name: Test conda install
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.11','3.12']
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
            token: ${{ secrets.GH_PAT }}

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          channels: conda-forge,defaults

      - name: Install with conda
        shell: bash -el {0}
        run: |
          conda env create -f environment.yml
          conda activate popopolus
          pip install pytest pytest-cov

      - name: Check help menu
        shell: bash -el {0}
        run: |
          conda activate popopolus
          popopolus --help

      - name: Run tests
        shell: bash -el {0}
        run: |
          conda activate popopolus
          pytest test/ --cov=popopolus --cov-report=xml


    # Revisit the idea of a codecov badge but check on app install specifics
    # - name: Upload coverage
    #    uses: codecov/codecov-action@v4
    #    with:
    #      token: ${{ secrets.CODECOV_TOKEN }}
    #      file: ./coverage.xml
    #      fail_ci_if_error: true

# some explicit diff checks on provided test data
#      - name: Create an array of the average allele balance in popultions
#        id: calc-freqs-check
#        run: |
#            popopolus calculate_pop_freqs -i tests/freqs/ex.vcf -o tests/freqs/popfreqs.txt tests/freqs/samplesheet
#            echo "sample output from build"
#            head tests/freqs/popfreqs.txt
#            echo "sample expected output"
#            head tests/freqs/expected_popfreqs.txt
#      - name: Run diff on tests
#        id: diff
#        run: |
#            #compare matrices and throw an exit code if not the same
#            if ! diff -q tests/freqs/popfreqs.txt tests/freqs/expected_popfreqs.txt; then
#                echo "allele frequency matrices do not match!"
#                diff tests/output/popfreqs.txt tests/output/expected_popfreqs.txt
#                exit 1
#            fi
#        shell: bash
        